### ISSUE TITLE
which routers?

### ISSUE THREAD

**Issue by tkellen** [jmeas/router-comparison#2]
can you link the headers of this table to the routers you're looking at? for example, is react router this https://github.com/rackt/react-router?

**Comment by jamesplease** [comment]
Good idea, @tkellen! I will do that.

Yup, that's the router for React. And the other one you might be unfamiliar with is StateRouter, which is my own WIP :stuck_out_tongue: 

It'll be missing a few features by design, but with a few hooks it'll be able to turned into a Router tightly integrated with a library like, say...Backbone :)

**Comment by jamesplease** [comment]
Resolved! Thanks for the suggestion @tkellen :)
