### ISSUE TITLE
Awesome work!

### ISSUE THREAD

**Issue by thebearingedge** [jmeas/router-comparison#27]
Hi,
Thanks for compiling this info! You might also check out @TehShrike's abstract-state-router. It is cool in that it attempts to decouple the actual components from their composition. That project inspired me to start writing screen-machine.

I started reading source on the other big projects for ideas on how to model the problem. I found your repos via the Backbone.Blazer Gitter room. I'm really grateful as your work will help my learning, thanks!

**Comment by TehShrike** [comment]
Oh wow, yeah, it looks like you're coming from a very similar place as I did @jmeas, though it looks like you're drawing on much broader experience than I was.

My main inspiration for the [abstract-state-router](https://github.com/TehShrike/abstract-state-router) was ui-router.

It looks like I agree with you in a lot of ways where ui-router fell short, though - its redirecting is poor (you can't redirect from resolve/async loading), it doesn't have good index/default states, abstract states are mostly dumb.

I left `.active` handling and template links to the template-specific libraries, though I've implemented it in all of them so far and tried to accommodate them.

Sorting was one thing I didn't put enough thought into before the first implementation.  Right now I'm using sorting by reverse order added, in order to fake sorting by deepest.

History is very much supported - right now it's through hashes only via the [hash-brown-router](https://github.com/TehShrike/hash-brown-router), but I'm looking into switching over to @mjackson's [history](https://github.com/rackt/history) module.

We should chat some time!  There's a [gitter chat for abstract-state-router](https://gitter.im/TehShrike/abstract-state-router), or I can also be on IRC.

**Comment by jamesplease** [comment]
> I'm really grateful as your work will help my learning, thanks!

Awesome! I'm glad it's useful for you!

> It looks like I agree with you in a lot of ways where ui-router fell short, though - its redirecting is poor (you can't redirect from resolve/async loading), it doesn't have good index/default states, abstract states are mostly dumb.

Haha. I wouldn't go so far as to say any of the features are dumb. My experience just lends itself to prefer certain approaches over others. My biggest concern is that I might be missing out on useful use cases for these features – I plan to do more investigating to find out if that's the case!

Throughout this process, I've already had many of my beliefs changed as I've dug into these features. There's always more to learn, it seems.

> I left .active handling and template links to the template-specific libraries, though I've implemented it in all of them so far and tried to accommodate them.

:+1: I was thinking of a similar approach.

> Sorting was one thing I didn't put enough thought into before the first implementation. Right now I'm using sorting by reverse order added, in order to fake sorting by deepest.

Ah, heh. It was my discovery of Ember's sorting algorithm over a year ago that prompted my interest in routing... :stuck_out_tongue:

> but I'm looking into switching over to @mjackson's history module.

Oh, nice. I hadn't heard of this one. Starred!

> We should chat some time! There's a gitter chat for abstract-state-router, or I can also be on IRC.

We def. should. I'll swing by the Gitter room :)
